version: '3.5'

services:

  node:
    image: golem-node/provider:dev
    build: .
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/.local/share/yagna/
    devices:
      - /dev/kvm:/dev/kvm
